export enum TipoTratamiento {
  INMUNOTERAPIA = 'INMUNOTERAPIA',
  PRUEBAS = 'PRUEBAS',
  GAMMAGLOBULINA = 'GAMMAGLOBULINA',
  VACUNAS_PEDIATRICAS = 'VACUNAS_PEDIATRICAS',
  MEDICAMENTOS_EXTRAS = 'MEDICAMENTOS_EXTRAS',
  CONSULTA = 'CONSULTA',
} 